spring:
  application:
    name: BlogApplication

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.default_schema: "blog"
      hibernate.jdbc.batch_size: 20
    database: postgresql

spring-doc:
  packagesToScan: com.example.BloggingApplication.Controller
  pathsToMatch: /**